config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'users/new'

  resource :session
  resources :entries, except: [:new, :create]
  resources :users do
  	resources :entries, only: [:new, :create]
  end

  root "entries#index"

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	if session[:user_id].present?
  		User.find(session[:user_id])
  	end
  end

  def require_user
  	unless logged_in?
  		flash[:error] = "You need to be logged in"
  		redirect_to root_path
  	end
  end

  def logged_in?
  	session[:user_id].present?
  end

  def current_user_owns_entry

    entry = Entry.find(params[:id])
    unless logged_in? and current_user == entry.user
      flash[:error] = "This post is private"
      redirect_to root_path   
    end
  end

  helper_method :current_user
  helper_method :require_user
  helper_method :logged_in?
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController



	def index
		@entries = Entry.all
	end

	def show
		current_user_owns_entry
		@entry = Entry.find(params[:id])
	end

	def new
  		@user = User.find(params[:user_id])
		@entry = @user.entries.new
	end

	def create
  		@user = User.find(params[:user_id])
		@entry = @user.entries.new(entry_params)
		if @entry.save
			flash[:success] = "That worked"
			redirect_to root_path
		else
			flash[:error] = "That didnt work"
			render :new
		end
	end

	def edit
		@entry = Entry.find(params[:id])
	end

	def update
		@entry = Entry.find(params[:id])
		if @entry.update(entry_params)
			flash[:success] = "That updated"
			redirect_to entry_path
		else
			flash[:error] = "That didnt work"
			render :new
		end
	end



	private
	def entry_params
		params.require(:entry).permit(
			:body,
			:mood,
			:visibility
		)
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create

  	@email = params[:session][:email]
  	@password = params[:session][:password]


  	@user = User.find_by(email: @email)


  	if @user.present? and @user.authenticate(@password)
  		flash[:success] = "Welcome back #{@user.email}"
  		session[:user_id] = @user.id
  		redirect_to root_path
  	else
  		flash[:error] = "Try again"
  		render :new  		
  	end
  end


  def destroy
  	reset_session
  	flash[:success] = "You have logged out"
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  	@user = User.new
  end

  def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "That worked"
			redirect_to root_path
		else
			flash[:error] = "That didnt work"
			render :new
		end
	end


	private
	def user_params
		params.require(:user).permit(
			:email,
			:password,
			:password_confirmation
		)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entries/edit.html.erb
<%= simple_form_for [@user, @entry] do |f| %>
	<%= f.input :body %>
	<%= f.input :mood, collection: [ "Good", "OK", "Bad"] %>
	<%= f.input :visibility, collection: [ "Public", "Anonymous", "Private"] %>
	<%= f.submit %>
<% end %>

app/views/entries/index.html.erb
<% unless logged_in? %>
	<h3>Welcome to Brain Dump</h3>
	<p>The place to record your thoughts</p>
	<ul>
		<li>Private, anonymous or public posting</li>
		<li>Track daily progress through mood recording</li>
		<li>See your progress and remember the feelings you had along the way</li>
	</ul>
	<%= link_to "Sign up", new_user_path %>
<% else %>

<% @entries.each do |entry| %>
	<% if logged_in? and current_user == entry.user %>
		<%= link_to entry_path(entry) do %>
			<p>
				<%= entry.body %><br/>
				<em><%= entry.created_at %></em>
			</p>
		<% end %>
	<% end %>
<% end %>

<%= link_to "New entry", new_user_entry_path(current_user.id) %>

<% end %>

app/views/entries/new.html.erb
<%= simple_form_for [@user, @entry] do |f| %>
	<%= f.input :body %>
	<%= f.input :mood, collection: [ "Good", "OK", "Bad"] %>
	<%= f.input :visibility, collection: [ "Public", "Anonymous", "Private"] %>
	<%= f.submit %>
<% end %>

app/views/entries/show.html.erb
<p>
<%= @entry.body %><br/>
<%= @entry.mood %><br/>
<%= @entry.visibility %><br/>
<em><%= @entry.created_at %></em>
</p>

<% if logged_in? and current_user == @entry.user %>
	<%= link_to "Edit", edit_entry_path(@entry) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<% if logged_in? %>
	<%= current_user.email %>
	<%= link_to "Me", root_path %>
	<%= link_to "New entry", new_user_entry_path(current_user.id) %>
	<%= link_to "Log out", session_path, method: :delete %>
<% else %>
	<%= link_to "Log in", new_session_path %>
	<%= link_to "Sign up", new_user_path %>
<% end %>

<% flash.each do |key, value| %>
	<div class="<%= key %>">
		<div class="wrapper">
			<p><%= value %></p>
		</div>
	</div>
<% end %>



<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<%= simple_form_for @user do |f| %>
	<%= f.input :email %>
	<%= f.input :password %>
	<%= f.submit %>
<% end %>